### ISSUE TITLE
"debugger" command was found in "dist/createRenderFn.js"

### ISSUE THREAD

**Issue by ysaaron** [jackmellis/vue-hoc#15]
I found this problem during installing package via npm.

But I didn't find this command in `src/createRenderFn.js`, is there any problem during you compiling the code to npm?

<img width="1096" alt="debugger" src="https://user-images.githubusercontent.com/16778946/37329146-85d68f4a-26d7-11e8-95aa-7dcee3205c02.png">

**Comment by jackmellis** [comment]
I'm not sure how that got in there (but not in the src). I've published 0.3.1 with the re-built dist

**Comment by ysaaron** [comment]
Thanks @jackmellis 

Would you publish this version to npm? I found even the version was updated on npm, but npm still detect `v0.3.0` for the latest version
