### ISSUE TITLE
Possible to wrap the contents of a slot?

### ISSUE THREAD

**Issue by Dylan-Chapman** [jackmellis/vue-hoc#16]
I'm extending a data table component. I'd like to be able for a HOC that wraps the table's "no-data" slot with an alert tag and a td tag, so I don't have to write the same wrapping tags  constantly. Is this possible? I tried to modify the slots in the renderWith options, but it didn't seem to take effect.

**Comment by jackmellis** [comment]
I haven't played around with slot hocs very much. Have you tried passing in a `scopedSlots` property to renderWith?

**Comment by Dylan-Chapman** [comment]
Thanks for the idea. Here's the best way I've found to handle it so far, but there may be a better way.

In ```renderWith``` I do the following:

```jsx
slots: {
  "no-data"( slots ) {
    if ( slots["no-data"] && slots["no-data"][0].tag !== "td" ) {
      if ( slots["no-data"][0].data ) {
        slots["no-data"][0].data.slot = null;
      }

      slots["no-data"] = [
        <td class="pa-0" colspan={this.headers.length} slot="no-data">
          <v-alert
            value={true}
            class="text-xs-left ma-0"
            type="info"
          >{slots["no-data"]}</v-alert>
        </td>
      ];
    }

    return slots["no-data"];
  }
}
```

Couple of notes:

1. I checked if the first element has a "td" tag because it will recursively wrap the same slot that has already been wrapped
2. I removed the upper-element's data.slot attribute, because if ```slot="no-data"``` is on anything besides a ```<template>``` tag, the slot data that's being wrapped will not appear after it's been wrapped (this one looks like a bug, but I don't know)
3. ```slots["no-data"]``` has to be set to an array, not just an element
4. I add ```slot="no-data"``` to my new wrapping element so that's it's properly detected by the base component
