### ISSUE TITLE
Don't import vue

### ISSUE THREAD

**Issue by titouancreach** [jackmellis/vue-hoc#20]
Here https://github.com/jackmellis/vue-hoc/blob/master/src/createHOC.js#L3 we are including Vue.
I think we can assume that the person that include vue-hoc already include Vue. Vue should maybe be an external variable. 
With this, we would be able to create npm package that doesn't include Vue in the bundle.

**Comment by jackmellis** [comment]
`vue` is only listed as a `peerDependency` of `vue-hoc` meaning that it will _never_ install vue itself. If your library seems to be including the entire vue build I would guess there's something not quite right with your build config - I haven't used microbundle before so I couldn't advise, but there will be something to do with external dependencies somewhere...

**Comment by titouancreach** [comment]
I will investigate then :) thanks for answering
