### ISSUE TITLE
named slots don't work correctly

### ISSUE THREAD

**Issue by jackmellis** [jackmellis/vue-hoc#30]
Currently if you create a HOC around a component that has named slots, all of the provided slots will be converted into default slots.

So instead of having
```js
{
  default: [ vNode ],
  header: [ vNode ],
  footer: [ vNode ],
}
```
you get
```js
{
  default: [ vNode, vNode, vNode ],
}
```

`normalizeSlots` should only be normalizing `default` slots. And I guess we should be doing something with `scopedSlots` instead...

**Comment by dieyidezui** [comment]
#36
