### ISSUE TITLE
[Question] Any way to access computed porperty of original component.

### ISSUE THREAD

**Issue by kashiif** [jackmellis/vue-hoc#35]
Thank you for the awesome work.

I am trying to access a computed property of the original component. Here is the code

```
import SourceComponent from '...';

const options = {
  methods: {
     myFunc() {
         console.log('computedRows', this.computedRows);
     }
  }
}

export default createHOC(SourceComponent, options, {});
```

Where `computedRows` is a computed property in the Source component. But the console line above prints `undefined`.

**Comment by jackmellis** [comment]
Hi kashiif

No, HOCs don't have access to the base component's internal properties (data, computed, methods, etc).

This is a design decision; an OOP class doesn't have access to its inherited class's private properties, for example. And from a practical pov, consider that at the point your HOC is created/rendered/etc, your base component won't have been created yet, so those computed properties won't exist.
