### ISSUE TITLE
Named slots problem and my solution

### ISSUE THREAD

**Issue by dieyidezui** [jackmellis/vue-hoc#36]
In order to create hoc with named slots, we should let the expression to be true:

```js
// vue/src/core/instance/render-helpers/resolve-slots.js
if ((child.context === context || child.functionalContext === context) &&
      data && data.slot != null
    ) {
  ...
}
```

So I saw vue-hoc did two things:

```js
// 1.
created(){
  this.$createElement = this.$parent.$createElement;
}

// 2.
normalizeSlots(this.$slots, this.$parent)
```

But sometimes, it didn't work because  of the hoc's `$parent` is not it's `$vnode.context`.

Although I don't known why, but I tried to fix it by：

```js
// 1.
created() {
  this.$createElement = this.$vnode.context.$createElement
  this._c = this.$vnode.context._c
}

// 2.
normalizeSlots(this.$slots, this.$vnode.context)
````

It works!

So, is this the correct way to solve this, or am I lost some special case.

**Comment by jackmellis** [comment]
After a fair few tests I've confirmed this works (I think). Should be publishing the fix shortly :+1:
